# Configuration file for Story Processor Application

# OpenAI Configuration
openai:
  settings:
    embedding_model: "text-embedding-ada-002"
    chat_model: "chatgpt-4o-latest"    
    timeout: 30.0
    max_tokens: 100000
    temperature: 0.7

# Qdrant Configuration
qdrant:
  settings:
    host: "localhost"
    port: 6333
    stories_collection:
      name: "stories_collection411"
      vector_size: 1536
      distance: "COSINE"
    reports_collection:
      name: "reports_collection411"
      vector_size: 1536
      distance: "COSINE"

# Prompts Configuration
prompts:
  report_refinement:
    system: |
      You are an expert AI assistant specializing in news analysis and report refinement. Your task is to enhance reports by integrating relevant Wikipedia information and providing comprehensive context.
    user: |
      Your goal is to refine and improve a generated report about a news story by effectively utilizing the provided Wikipedia information to add context and depth.

      **Original Story:**
      {original_story}

      **Generated Report:**
      {generated_report}

      **Wikipedia Information:**
      {wikipedia_info}

      Please perform the following tasks:

      1. **Integrate Wikipedia Information:**  
         - Seamlessly incorporate the relevant Wikipedia information into the generated report.
         - Ensure that the added content enhances the understanding of the story by providing:
           - Historical background of locations or organizations mentioned.
           - Explanations of technical terms or concepts.
           - Relevant past events or trends related to the current story.
           - Biographical information about key figures, if applicable.

      2. **Enhance Clarity and Coherence:**  
         - Improve the overall flow and readability of the report.
         - Ensure that the integration of additional information does not disrupt the narrative but instead enhances it.

      3. **Fact-Check and Correct Inaccuracies:**  
         - Cross-reference the original report with the Wikipedia information to identify and correct any inaccuracies or misinterpretations.

      4. **Ensure Relevance of Entities:**  
         - Verify that all entities mentioned in the report are directly related to the story.
         - Remove or minimize references to entities that do not contribute to the core narrative or analysis.

      5. **Summarize Integrated Information:**  
         - At the end of the report, provide a concise summary of all the integrated Wikipedia articles.
         - Highlight the key points from each article that were utilized in enhancing the report.

      **Deliverable:**  
      Provide a refined version of the report that incorporates the above enhancements, effectively utilizing Wikipedia information to create a more informative and contextually rich analysis.

  summary_generation:
    system: |
      You are an expert AI assistant specializing in summarizing multiple reports into a cohesive summary. Your task is to distill the essential points from each report to create a comprehensive and concise summary.
    user: |
      Please create a comprehensive summary based on the following refined reports:

      {reports}

      Ensure that the summary:
      
      - Captures the key insights and findings from each individual report.
      - Highlights common themes, trends, and significant points across all reports.
      - Maintains clarity and coherence, providing a clear overview without unnecessary detail.
      - Reflects the enhanced context and information derived from Wikipedia integrations in the individual reports.

      **Deliverable:**  
      Provide a concise and informative summary that encapsulates the key points from all the refined reports, offering a comprehensive overview of the analyzed stories.
